sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[笔记](/notes/)'
    more: '[更多](/about/)'

article:
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
    '设计开发': '#03a9f4'
    # '奇思妙想': '#009688'
    '解决方案': '#ff9800'
    '技术加油站': '#4caf50'
    '开源库': '#4caf50'
    '博客主题': '#ffa000'
    # '应用程序': '#e91e63'
    # '实用脚本': '#009688'
  share: [wechat, weibo, email, link]
  related_posts:
    enable: true

comments:
  service: utterances # utterances
  utterances:
    repo: xaoxuu/blog-comments

footer:
  social:
    - icon: '<img src="https://7.dusays.com/2021/02/14/25678f144c438.svg"/>'
      url: /atom.xml
    - icon: '<img src="https://7.dusays.com/2021/02/14/08a41b181ce68.svg"/>'
      url: https://github.com/xaoxuu
    - icon: '<img src="https://7.dusays.com/2021/02/14/cf1ae151f9e83.svg"/>'
      url: https://music.163.com/#/user/home?id=63035382
    - icon: '<img src="https://7.dusays.com/2021/02/14/942ebbf1a4b91.svg"/>'
      url: /about/#comments
  source: '[GitHub](https://github.com/xaoxuu/xaoxuu.github.io/)'
